Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using CafeAPI.Models;
using CafeAPI.Repo;
using CafeAPI.Extension;

namespace CafeAPI.Controllers
{
    public class AreasController : Controller
    {
        private readonly AreaRepo _areaRepo;

        public AreasController(IConfiguration configuration)
        {
            _areaRepo = new AreaRepo(configuration);
        }

        // GET: Area
        public IActionResult Index()
        {
            var result = _areaRepo.FindAll();
            return View(result);
        }

        // GET: Area/Details/5
        public IActionResult Details(int? id)
        {
            return View();
        }

        // GET: Area/Create
        public IActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            else
            {
                return View();
            }
        }

        // POST: Area/Create
        [HttpPost]
        public IActionResult Create(Area model)
        {
            if (ModelState.IsValid)
            {
                _areaRepo.Add(model);
                return RedirectToAction("Index");
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView(model);
            }
            else
            {
                return View(model);
            }
        }

        // GET: /Area/Edit/1
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Area area = _areaRepo.FindByID(id.Value);

            if (Request.IsAjaxRequest())
            {
                return PartialView(area);
            }
            else
            {
                return View(area);
            }
        }

        // POST: /Area/Edit   
        [HttpPost]
        public IActionResult Edit(Area model)
        {
            if (ModelState.IsValid)
            {
                _areaRepo.Update(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET:/Area/Delete/1
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _areaRepo.Remove(id.Value);
            return RedirectToAction("Index");
        }

        //var sUnit = _dappConn.Query<MasterUnit>(@"SELECT UnitID, UnitName FROM MasterUnit");
        //ViewBag.UnitID = new SelectList(sUnit.AsQueryable(), "UnitID", "UnitName");

        //var sArea = IDbCommand
    }
}

Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Npgsql;
using CafeAPI.Models;
using CafeAPI.Repo;
using CafeAPI.Extension;

namespace CafeAPI.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CategoryRepo _categoryRepo;

        public CategoryController(IConfiguration configuration)
        {
            _categoryRepo = new CategoryRepo(configuration);
        }

        public IActionResult Index()
        {
            List<Category> category = (List<Category>)_categoryRepo.FindAll();
            return View(category);
        }

        [HttpPost]
        public JsonResult LoadData()
        {
            List<Category> category = _categoryRepo.FindAll();
            return Json(new { data = category });
        }

        public IActionResult Create()
        {

            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Create(Category model)
        {
            if (ModelState.IsValid)
            {
                _categoryRepo.Add(model);
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category category = _categoryRepo.FindByID(id.Value);
            if (category == null)
            {
                return NotFound();
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView(category);
            }
            else
            {
                return View(category);
            }
        }

        [HttpPost]
        public IActionResult Edit(Category model)
        {
            if (ModelState.IsValid)
            {
                _categoryRepo.Update(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            _categoryRepo.Remove(id.Value);
            return RedirectToAction("Index");
        }

    }
}

Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using CafeAPI.Models;
using CafeAPI.Repo;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Net.Http.Headers;

namespace CafeAPI.Controllers
{
    public class MenusController : Controller
    {
        private readonly MenusRepo _menusRepo;
        private readonly CategoryRepo _categoryRepo;
        private readonly IHostingEnvironment _hostingEnvironment;

        public MenusController(IConfiguration configuration, IHostingEnvironment hostingEnvironment)
        {
            _menusRepo = new MenusRepo(configuration);
            _categoryRepo = new CategoryRepo(configuration);
            this._hostingEnvironment = hostingEnvironment;
        }

        [HttpPost]
        public JsonResult LoadData()
        {
            List<Menus> menus = _menusRepo.GetJoinWith();
            return Json(new { data = menus });
        }

        // GET: Menus
        public IActionResult Index()
        {
            //List<Menus> menus = (List<Menus>)_menusRepo.FindAll();
            //return View(_menusRepo.FindAll());
            List<Menus> menus = _menusRepo.GetJoinWith();
            return View(menus);
        }

        // GET: Etalase
        public IActionResult Etalase()
        {
            List<Menus> menus = _menusRepo.GetJoinWith();
            return View(menus);
        }

        // GET: Menus/Create
        public IActionResult Create()
        {
            ViewBag.Category = new SelectList(_categoryRepo.FindAll(), "ID", "CategoryName");

            return View();
        }

        // POST: Menus/Create
        [HttpPost]
        public IActionResult Create(Menus model)
        {
            if (ModelState.IsValid)
            {
                var newFileName = string.Empty;

                if (HttpContext.Request.Form.Files != null)
                {
                    var fileName = string.Empty;
                    string fileNameEmpty = "noimages.png";

                    var files = HttpContext.Request.Form.Files;

                    foreach (var file in files)
                    {
                        if (file.Length > 0)
                        {
                            //Getting FileName
                            fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                            //Assigning Unique Filename (Guid)
                            //var myUniqueFileName = Convert.ToString(Guid.NewGuid());

                            //Getting file Extension
                            var fileExtension = Path.GetExtension(fileName);

                            // concating  FileName + FileExtension
                            //newFileName = myUniqueFileName + fileExtension;
                            if (fileName != string.Empty)
                            {
                                newFileName = fileName;
                            }
                            else {
                                newFileName = fileNameEmpty;
                            }

                            // Combines two strings into a path.
                            //fileName = Path.Combine(_hostingEnvironment.WebRootPath, "upload/images") + $@"\{newFileName}";
                            fileName = Path.Combine(_hostingEnvironment.WebRootPath) + $@"\{newFileName}";

                            // if you want to store path of folder in database
                            //model.MenuImg = "upload/images/" + newFileName;
                            model.MenuImg = newFileName;

                            using (FileStream fs = System.IO.File.Create(fileName))
                            {
                                file.CopyTo(fs);
                                fs.Flush();
                            }
                        }
                    }
                }

                #region Menus Class
                //Menus menus = new Menus
                //{                                                                    //// Menus menus = new Menus();
                //    MenuName = model.MenuName,                  //// menus.MenuName = model.MenuName;
                //    Category = model.Category,                        //// menus.Category = model.Category;
                //    MenuPrice = model.MenuPrice,                    //// menus.MenuPrice = model.MenuPrice;
                //    MenuStock = model.MenuStock,                  //// menus.MenuStock = model.MenuStock;
                //    MenuDesc = model.MenuDesc,                    //// menus.MenuDesc = model.MenuDesc;
                //    MenuImg = uniqueFileName,                      //// menus.MenuImg = uniqueFileName;
                //    MenuType = model.MenuType,                   //// menus.MenuType = model.MenuType;
                //    created_at = model.created_at,                 //// menus.created_at = model.created_at;
                //    updated_at = model.updated_at                //// menus.updated_at = model.updated_at;
                //}; 
                #endregion

                _menusRepo.Add(model);
                return RedirectToAction("Index");
                //return RedirectToAction("Edit", new { id = model.ID });
            }

            ViewBag.Category = new SelectList(_categoryRepo.FindAll(), "ID", "CategoryName");

            return View(model);
        }

        // GET: /Menus/Edit/1
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Menus menus = _menusRepo.FindByID(id.Value);
            ViewBag.Category = new SelectList(_categoryRepo.FindAll(), "ID", "CategoryName", menus.Category);

            return View(menus);
        }

        // POST: /Menus/Edit   
        [HttpPost]
        public IActionResult Edit(Menus model)
        {
            if (ModelState.IsValid)
            {
                #region try using IFormFile
                //if (Request.Form.Files.Count > 0)
                //{
                //    var oldImagesPath = model.MenuImgVM;
                //    string uniqueFileName = null;

                //    if (model != null || model.MenuImgVM.Length > 0)
                //    {
                //        string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "~/upload/images");
                //        uniqueFileName = Guid.NewGuid().ToString() + "_" + model.MenuImgVM.FileName;       //// using Guid to have unique name..
                //        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                //        model.MenuImgVM.CopyTo(new FileStream(filePath, FileMode.Create));

                //    }
                //}

                //Menus menus = new Menus
                //{
                //    MenuName = model.MenuName,
                //    Category = model.Category,
                //    MenuPrice = model.MenuPrice,
                //    MenuStock = model.MenuStock,
                //    MenuDesc = model.MenuDesc,
                //    //MenuImg = uniqueFileName,
                //    MenuType = model.MenuType,
                //    created_at = model.created_at,
                //    updated_at = model.updated_at
                //};
                #endregion

                var newFileName = string.Empty;

                if (HttpContext.Request.Form.Files != null)
                {
                    string fileName = string.Empty;
                    var iFoFiles = HttpContext.Request.Form.Files;

                    foreach (var file in iFoFiles)
                    {
                        if (file.Length > 0)
                        {
                            //initiate previous file
                            string oldImagesPath = Path.Combine(_hostingEnvironment.WebRootPath, model.MenuImg);

                            //Getting FileName
                            fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                            //Getting file Extension
                            string fileExtension = Path.GetExtension(fileName);

                            // concating  FileName + FileExtension
                            //newFileName = myUniqueFileName + fileExtension;
                            newFileName = fileName;

                            // Combines two strings into a path.
                            //fileName = Path.Combine(_hostingEnvironment.WebRootPath, "upload/images") + $@"\{newFileName}";
                            fileName = Path.Combine(_hostingEnvironment.WebRootPath) + $@"\{newFileName}";

                            //if (System.IO.File.Exists(oldImagesPath) && newFileName == oldImagesPath)
                            if (oldImagesPath != null)
                            {
                                System.IO.File.Delete(oldImagesPath);
                            }

                            // if you want to store path of folder in database
                            //model.MenuImg = "upload/images/" + newFileName;
                            model.MenuImg = newFileName;

                            using (FileStream fs = System.IO.File.Create(fileName))
                            {
                                file.CopyTo(fs);
                                fs.Flush();
                            }
                        }
                    }
                }

                _menusRepo.Update(model);
                return RedirectToAction("Edit");
            }

            ViewBag.Category = new SelectList(_categoryRepo.FindAll(), "ID", "CategoryName", model.Category);

            return View(model);
        }

        // GET:/Menus/Delete/1

Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Npgsql;
using CafeAPI.Models;
using CafeAPI.Repo;
using CafeAPI.Extension;

namespace CafeAPI.Controllers
{
    public class TablesController : Controller
    {
        private readonly TablesRepo _tablesRepo;

        public TablesController(IConfiguration configuration)
        {
            _tablesRepo = new TablesRepo(configuration);
        }

        public IActionResult Index()
        {            
            List<Tables> tables = (List<Tables>)_tablesRepo.FindAll();
            return View(tables);
        }

        [HttpPost]
        public JsonResult LoadData()
        {
            List<Tables> tables = _tablesRepo.FindAll();
            return Json(new { data = tables });
        }

        public IActionResult Create()
        {

            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Create(Tables model)
        {
            if (ModelState.IsValid)
            {
                _tablesRepo.Add(model);
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Tables tables = _tablesRepo.FindByID(id.Value);
            if (tables == null)
            {
                return NotFound();
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView(tables);
            }
            else
            {
                return View(tables);
            }
        }

        [HttpPost]
        public IActionResult Edit(Tables model)
        {
            if (ModelState.IsValid)
            {
                _tablesRepo.Update(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            _tablesRepo.Remove(id.Value);
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_AdminLeftNav.cshtml
<div id="left-menu">
    <div class="sub-left-menu scroll">
        <ul class="nav nav-list">
            <li><div class="left-bg"></div></li>
            <li class="time">
                <h1 class="animated fadeInLeft">21:00:59</h1>
                <p class="animated fadeInRight">Sat,October 1st 2029</p>
            </li>
            <li class="ripple">
                <a asp-controller="EventCalendar" asp-action="Index">
                    <span class="fa fa-calendar-o"></span>Calendar Events
                </a>
            </li>
            <li class="active ripple">
                <a class="tree-toggle nav-header">
                    <span class="fa-home fa"></span> Dashboard
                    <span class="fa-angle-right fa right-arrow text-right"></span>
                </a>
                <ul class="nav nav-list tree">
                    <li><a href="dashboard-v1.html">Dashboard v.1</a></li>
                    <li><a href="dashboard-v2.html">Dashboard v.2</a></li>
                </ul>
            </li>
            <li class="ripple">
                <a class="tree-toggle nav-header">
                    <span class="fa-area-chart fa"></span> Master Data
                    <span class="fa-angle-right fa right-arrow text-right"></span>
                </a>
                <ul class="nav nav-list tree">

                    <li>
                        <a asp-controller="Areas" asp-action="Index">
                            List Area
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Customers" asp-action="Index">
                            List Customer
                        </a>
                    </li>
                </ul>
            </li>
            <li class="ripple">
                <a class="tree-toggle nav-header">
                    <span class="fa fa-pencil-square"></span> Settings  <span class="fa-angle-right fa right-arrow text-right"></span>
                </a>
                <ul class="nav nav-list tree">
                    <li>
                        <a asp-controller="Tables" asp-action="Index">
                            Tables Settings
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Category" asp-action="Index">
                            Category Menus
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Menus" asp-action="Index">
                            List Menus
                        </a>
                    </li>
                </ul>
            </li>
            <li class="ripple">
                <a class="tree-toggle nav-header"><span class="fa fa-check-square-o"></span> Transaksi  <span class="fa-angle-right fa right-arrow text-right"></span> </a>
                <ul class="nav nav-list tree">
                    <li>
                        <a asp-controller="Menus" asp-action="Etalase">
                            Etalase Menus
                        </a>
                    </li>
                    <li><a href="#">Wizard</a></li>
                    <li><a href="#">File Upload</a></li>
                    <li><a href="#">Text Editor</a></li>
                </ul>
            </li>
            <li><a href="credits.html">Credits</a></li>
            @*<li>
                <a asp-controller="KlhkSents" asp-action="Index">
                    List Data Sents to KLHK
                </a>
            </li>*@
            @*<li>
                <a asp-controller="KlhkSentsApi" asp-action="Get">
                    API GetAll Sents Data List
                </a>
            </li>*@
        </ul>
    </div>
</div>

Views/Shared/_HeaderNav.cshtml
<nav class="navbar navbar-default header navbar-fixed-top">
    <div class="col-md-12 nav-wrapper">
        <div class="navbar-header" style="width:100%;">
            <div class="opener-left-menu is-open">
                <span class="top"></span>
                <span class="middle"></span>
                <span class="bottom"></span>
            </div>
            <a asp-controller="home" asp-action="index" class="navbar-brand">
                <b>Teras PRAJA</b>
            </a>

            <ul class="nav navbar-nav search-nav">
                <li>
                    <div class="search">
                        <span class="fa fa-search icon-search" style="font-size:23px;"></span>
                        <div class="form-group form-animate-text">
                            <input type="text" class="form-text" required>
                            <span class="bar"></span>
                            <label class="label-search">Type anywhere to <b>Search</b> </label>
                        </div>
                    </div>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right user-nav">
                <li class="user-name"><span>mimin</span></li>
                <li class="dropdown avatar-dropdown">
                    <img src="asset/img/avatar.jpg" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" />
                    <ul class="dropdown-menu user-dropdown">
                        <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                        <li><a href="#"><span class="fa fa-calendar"></span> My Calendar</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="more">
                            <ul>
                                <li><a href=""><span class="fa fa-cogs"></span></a></li>
                                <li><a href=""><span class="fa fa-lock"></span></a></li>
                                <li><a href=""><span class="fa fa-power-off "></span></a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#" class="opener-right-menu"><span class="fa fa-coffee"></span></a></li>
            </ul>
        </div>
    </div>
</nav>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="description" content="Miminium Admin Template v.1">
    <meta name="author" content="Isna Nur Azis">
    <meta name="keyword" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Teras PRAJA - Cafe</title>

    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="~/asset/css/bootstrap.min.css">

    <!-- plugins -->
    <link rel="stylesheet" type="text/css" href="~/asset/css/plugins/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/asset/css/plugins/summernote.css" />
    <link rel="stylesheet" hidden-sm type="text/css" href="~/asset/css/plugins/animate.min.css" />
    <link href="~/asset/css/style.css" rel="stylesheet">
    <!-- end: Css -->

    <link rel="shortcut icon" href="asset/img/logomi.png">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    <script src="~/asset/js/jquery.min.js"></script>
</head>

<body id="mimin" class="dashboard">
    <!-- start: Header -->
    @await Html.PartialAsync("_HeaderNav")
    <!-- end: Header -->

    <div class="container-flTableCode mimin-wrapper">

        <!-- start:Left Menu -->
        @await Html.PartialAsync("_AdminLeftNav")
        <!-- end: Left Menu -->
        <!-- start: Content -->

        <div id="content">
            <div class="panel box-shadow-none content-header">
                <div class="panel-body">
                    <div class="col-md-12">
                        <p class="animated fadeInDown">
                            <h5>@await Html.PartialAsync("_SiteMapPathHelperModel")</h5>
                        </p>
                    </div>
                </div>
            </div>

            <div class="form-element">
                <div class="col-md-12 padding-0">
                    <div class="col-md-12">
                        <div class="panel form-element-padding">
                            <div class="panel-heading">
                                <h4>@await Html.PartialAsync("_SiteMapHeaderHelperModel")</h4>
                            </div>
                            <div class="panel-body" style="padding-bottom:30px;">

                                @RenderBody()

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- end: content -->
        <!-- start: right menu -->
        @await Html.PartialAsync("_RightNav")
        <!-- end: right menu -->
    </div>

    <!-- start: Mobile -->
    @await Html.PartialAsync("_MobileNav")
    <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
    </button>
    <!-- end: Mobile -->
    <!-- start: Javascript -->
    <script src="~/asset/js/jquery.ui.min.js"></script>
    <script src="~/asset/js/bootstrap.min.js"></script>

    <!-- plugins -->
    <script src="~/asset/js/plugins/moment.min.js"></script>
    <script src="~/asset/js/plugins/summernote.min.js"></script>
    <script src="~/asset/js/plugins/jquery.nicescroll.js"></script>
    <script src="~/asset/js/plugins/jquery.validate.min.js"></script>
    <script src="~/asset/js/plugins/jquery.validate.unobtrusive.min.js"></script>

    <!-- custom -->
    <script src="~/asset/js/main.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#summernote').summernote({
                height: 400
            });
        });
    </script>
    <!-- end: Javascript -->
</body>
</html>

Views/Shared/_SiteMapHeaderHelperModel.cshtml
@*      SiteMapPath - Header    *@


@if (ViewContext.RouteData.Values["controller"].ToString() != "Home")
{
    @Html.ActionLink(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["controller"].ToString())
}

@if (ViewContext.RouteData.Values["action"].ToString() != "Index")
{
    @Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index", ViewContext.RouteData.Values["controller"].ToString())
}
else
{
    @Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index", ViewContext.RouteData.Values["controller"].ToString())
}

Views/Shared/_SiteMapPathHelperModel.cshtml
@*      SiteMapPath - Breadcrumb    *@


@Html.ActionLink("Home", "Index", "Home")

@if (ViewContext.RouteData.Values["controller"].ToString() != "Home")
{
    @: >  @Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index", ViewContext.RouteData.Values["controller"].ToString())
}

@if (ViewContext.RouteData.Values["action"].ToString() != "Index")
{
    @: > @Html.ActionLink(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["controller"].ToString())
}