Models/EventCalendar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CafeAPI.Models
{
    public class EventCalendar : BaseEntity
    {
        [Key]
        public int ID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public System.DateTime StartEvent { get; set; }
        public Nullable<System.DateTime> EndEvent { get; set; }
        public string ThemeColor { get; set; }
        public bool IsFullDay { get; set; }
    }
}

Controllers/EventCalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CafeAPI.Extension;
using CafeAPI.Models;
using CafeAPI.Repo;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace CafeAPI.Controllers
{
    public class EventCalendarController : Controller
    {
        private readonly EventCalendarRepo _eventCalendarRepo;       

        public EventCalendarController(IConfiguration configuration)
        {
            _eventCalendarRepo = new EventCalendarRepo(configuration);
        }

        [HttpPost]
        public JsonResult LoadData()
        {
            List<EventCalendar> eventCalendar = _eventCalendarRepo.FindAll();
            return Json(eventCalendar);
        }

        // GET: EventCalendar
        public IActionResult Index()
        {
            List<EventCalendar> events = _eventCalendarRepo.FindAll();
            return View(events);
        }

        // GET: EventCalendar/Details/5
        public IActionResult Details(int? id)
        {
            return View();
        }

        // GET: EventCalendar/Create
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            else
            {
                return View();
            }
        }

        // POST: EventCalendar/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EventCalendar model)
        {
            if (ModelState.IsValid)
            {
                try {
                    _eventCalendarRepo.Add(model);
                    return RedirectToAction("Index");
                }
                catch (Exception ex) {
                    throw ex;
                }
            }

            return View();
        }

        // GET: EventCalendar/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            EventCalendar eventCalendar = _eventCalendarRepo.FindByID(id.Value);

            if (Request.IsAjaxRequest())
            {
                return PartialView(eventCalendar);
            }
            else
            {
                return View(eventCalendar);
            }
        }

        // POST: EventCalendar/Edit/5
        [HttpPost]
        public IActionResult Edit(EventCalendar model)
        {
            if (ModelState.IsValid)
            {
                _eventCalendarRepo.Update(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // POST: EventCalendar/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == 0) {
                return NotFound();
            }

            try {
                _eventCalendarRepo.Remove(id.Value);
                return RedirectToAction("Index");
            }
            catch(Exception ex) {
                throw ex;
            }
        }
    }
}

Views/EventCalendar/Create.cshtml
@model EventCalendar

@{
    ViewData["Title"] = "Create";
}


<form asp-action="Create" id="myForm">
    <div class="form-group">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Subject" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Subject" class="form-control android" />
                <span asp-validation-for="Subject" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control android" />
                <span asp-validation-for="Description" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="StartEvent" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="StartEvent" class="form-control android" />
                <span asp-validation-for="StartEvent" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EndEvent" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EndEvent" class="form-control android" />
                <span asp-validation-for="EndEvent" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IsFullDay" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IsFullDay"  />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ThemeColor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ThemeColor" class="form-control android" type="color" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn ripple-infinite btn-raised btn-success" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/EventCalendar/Edit.cshtml
@model  EventCalendar

@{
    ViewData["Title"] = "Edit";
}


<form asp-action="Edit" id="myForm">
    <div class="form-group">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="ID" type="hidden" />

        <div class="form-group">
            <label asp-for="Subject" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Subject" class="form-control android" />
                <span asp-validation-for="Subject" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control android" />
                <span asp-validation-for="Description" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="StartEvent" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="StartEvent" class="form-control android" />
                <span asp-validation-for="StartEvent" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EndEvent" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EndEvent" class="form-control android" />
                <span asp-validation-for="EndEvent" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IsFullDay" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IsFullDay" class="  " />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ThemeColor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ThemeColor" class="form-control android" type="color" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn ripple-infinite btn-raised btn-success" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/EventCalendar/Index.cshtml
@model IEnumerable<EventCalendar>

@{
    ViewData["Title"] = "Index";
}

<div class="col-md-8">
    <div class="panel box-v4">
        <div class="panel-heading bg-white border-none">
            <h3><span class="icon-notebook icons"></span>Agenda Events on Teras PRAJA</h3>
        </div>
        <div class="panel-body padding-0">
            @*<div class="col-md-12 col-xs-12 col-md-12 padding-0 box-v4-alert">
                    <h2>Checking Your Server!</h2>
                    <p>Daily Check on Server status, mostly looking at servers with alerts/warnings</p>
                    <b><span class="icon-clock icons"></span> Today at 15:00</b>
                </div>*@
            <div id="calender" class="calendar">
            </div>
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="panel box-v4">
        <div class="panel-heading bg-white border-none">
            <h3><span class="icon-notebook icons"></span>Upcoming Agenda</h3>
        </div>
        <div class="panel-body padding-0">
            <table id="myTable" class="table compact stripe hover order-column responsive">
                <thead>
                    <tr>
                        <th colspan="3">
                            <a asp-controller="EventCalendar" asp-action="Create" class="btn btn-success" id="btnCreate">Add New Agenda Events</a>
                        </th>
                    </tr>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.StartEvent)
                        </th>
                        <th width="200px">
                            @Html.DisplayNameFor(model => model.Subject)
                        </th>
                        <th width="100px">-</th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.StartEvent
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Subject)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ID" class="">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.ID"
                               class="btn-danger"
                               onclick="return confirm('Are you sure wants to delete @item.Subject ?');">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <p id="pDetails"></p>
            </div>
            <div class="modal-footer">
                @foreach (var item in Model)
                {
                    <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-info" id="btnEdit">Update</a>
                }
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" type="text/css" href="~/asset/css/plugins/fullcalendar.min.css" />
<link href="~/asset/css/plugins/fullcalendar.print.min.css" rel="stylesheet" media="print" />
<script src="~/asset/js/plugins/moment.min.js"></script>
<script src="~/asset/js/plugins/fullcalendar.min.js"></script>
<script src="~/scripts/IndexEventCalendar.js"></script>